Author: Edward Moradian<br>
Date: 09/14/2018<br>

### This tutorial illustrates three different ways to calculate a distance matrix.

**Problem.** Let A and B be matrices that their columns represent entries/coordinates/features of samples all having the same dimensionality and each row represents a vector/sample. You can use numpy random method to create such matrices.

In [482]:
np.random.seed(seed=1)

A = np.random.randn(1000,50)
B = np.random.randn(5000,50)

In [480]:
# Test data
import numpy as np

A = np.array([[0,0],[4,4]])
B = np.array([[1,1],[0,0],[1,1],[2,2]])

**Part 1.** Use for loops to find the pairwise distance of each vector in A from each vector in B.

In [483]:
import numpy as np

def loop_dist(A,B):
    
    n = len(A)    # n is the number of rows in A
    m = len(B)    # m is the number of rows in B
    l = len(A[0]) # l is the number of columns in A which is the same as B
    vector_distance_2 = np.zeros((n,m))    # Initialize an empty matrix of zeros in the shape of (n,m), n x m matrix

    
    for i in range(n):             
        for j in range(m):
            vector_distance_1 = 0
            for k in range(l):
                vector_distance_1 += (A[i,k]-B[j,k])**2
            vector_distance_2[i,j] = (vector_distance_1)**(1/2)    # input the distance into the correct matrix element
    return vector_distance_2

In [484]:
dist_w_loop = loop_dist(A,B)
dist_w_loop

array([[11.05274066, 10.38876466, 10.16663561, ...,  9.40609189,
         9.98343736,  9.24938432],
       [ 9.45975945,  9.67015416,  8.02972644, ...,  8.35375709,
         9.26134481,  9.12936845],
       [ 9.10412115,  9.94540619, 10.33590363, ...,  9.54935886,
         8.98421158,  8.8744184 ],
       ...,
       [ 8.61994485, 10.24009112, 10.36815424, ..., 10.22758393,
         8.89727869, 10.29262723],
       [10.56744549,  9.95653534,  9.7496924 , ..., 10.2086809 ,
         8.89732519,  9.98095355],
       [10.26401403,  9.53785915,  9.54423071, ...,  8.45891164,
         9.12512204,  8.72211447]])

**Part 2.** Use only functions provided in numpy to calculate to find the pairwise distances in a vectorized fashion. You shouldn't use any loops or any other library except numpy.

In [493]:
import numpy as np

def vect_dist(A,B):
    vector_distance = np.sum((A[:,None] - B[None, :])**2, -1)**0.5
    return vector_distance

In [510]:
dist_w_vec = vect_dist(A,B)
dist_w_vec

array([[11.05274066, 10.38876466, 10.16663561, ...,  9.40609189,
         9.98343736,  9.24938432],
       [ 9.45975945,  9.67015416,  8.02972644, ...,  8.35375709,
         9.26134481,  9.12936845],
       [ 9.10412115,  9.94540619, 10.33590363, ...,  9.54935886,
         8.98421158,  8.8744184 ],
       ...,
       [ 8.61994485, 10.24009112, 10.36815424, ..., 10.22758393,
         8.89727869, 10.29262723],
       [10.56744549,  9.95653534,  9.7496924 , ..., 10.2086809 ,
         8.89732519,  9.98095355],
       [10.26401403,  9.53785915,  9.54423071, ...,  8.45891164,
         9.12512204,  8.72211447]])

**Part 3.** Compare the solutions of the two methods to make sure you get the same answer. Then compare the efficiency of the two methods using *timeit*.

In [503]:
%timeit loop_dist(A,B)

4min 14s ± 655 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [504]:
%timeit vect_dist(A,B)

1min 37s ± 18.1 s per loop (mean ± std. dev. of 7 runs, 1 loop each)


The vectorized distance matrix function was about 2.61856 times as fast as the looped distance matrix function.

In [508]:
import numpy as py
np.min(np.isclose(dist_w_vec, dist_w_loop,atol=.0001))

True

The looped distance matrix and the vectorized distance matrix are equivalent.

**Part 4.** Use scikit-learn package to do the same calculation and compare the efficiency with the previous methods.

In [499]:
import sklearn
from sklearn.metrics.pairwise import euclidean_distances

def sk_dist(A,B):
    sk_dist_formula = sklearn.metrics.pairwise.euclidean_distances(A,B)
    return sk_dist_formula

In [500]:
dist_w_sk = sk_dist(A,B)
dist_w_sk

array([[11.05274066, 10.38876466, 10.16663561, ...,  9.40609189,
         9.98343736,  9.24938432],
       [ 9.45975945,  9.67015416,  8.02972644, ...,  8.35375709,
         9.26134481,  9.12936845],
       [ 9.10412115,  9.94540619, 10.33590363, ...,  9.54935886,
         8.98421158,  8.8744184 ],
       ...,
       [ 8.61994485, 10.24009112, 10.36815424, ..., 10.22758393,
         8.89727869, 10.29262723],
       [10.56744549,  9.95653534,  9.7496924 , ..., 10.2086809 ,
         8.89732519,  9.98095355],
       [10.26401403,  9.53785915,  9.54423071, ...,  8.45891164,
         9.12512204,  8.72211447]])

In [511]:
# check if the answers are the same
np.min(np.isclose(dist_w_vec, dist_w_sk,atol=.0001))
np.min(np.isclose(dist_w_loop, dist_w_sk,atol=.0001))

True

All of the distance matrices are the same among the different functions.

In [506]:
%timeit sk_dist(A,B)

79.1 ms ± 2.79 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


With scikit learn, the distance matrix function is about 3215.18 times as fast as the looped distance matrix function.  Also, the distance matrix function is about 1227.84 times as fast as the vectorized distance function.

### Conclusion

Using vectorization methods are orders of magnitude faster than using logical loops (witness the power of linear algebra and hardware acceleration). Vectorization also makes the code much more readable and generalizable to future applicaitons.

For linear algebra you can use a for loop, but it is not efficient.  In this exercise, the functions with loops were magnitudes times slower than the functions in vectorized fashion.  Vectorization is much more efficient.  The Numpy package allows for efficient computation.  Numpy does not want user to use for loops.  